#==============================================================================
#
# DESCRIPTION: Recipe extending a Grid'5000 environment recipe supported by
# the technical team. The build will be similar to the one of the supported
# environments, involving puppet notably.
#
#==============================================================================
# This recipe extends another. To look at the step involed, run:
#   kameleon build -d ubuntu2204-dont-throw-the-stack.yaml
# To see the variables that you can override, use the following command:
#   kameleon info ubuntu2204-dont-throw-the-stack.yaml
---
extend: grid5000/ubuntu2004-x64-common.yaml

global:
        ### Uncomment and adapt the global variables below as needed

        ## Export format to generate
        # appliance_formats: qcow2 tar.zst

        ## Environment description customization
        ## Author
        # g5k_author: "john.doe@grid5000.fr"
        ## Version
        # g5k_version: 1
        ## Environment image path and compression
        # g5k_tar_path: local:///path/to/your/image
        # g5k_tar_compression: "zstd"
        ## Environment postinstall path, compression, and script command
        # g5k_postinst_path: server:///grid5000/postinstalls/g5k-postinstall.tgz
        # g5k_postinst_compression: "gzip"
        # g5k_postinst_script: g5k-postinstall --net debian
        ## Environment kernel path and params
        # g5k_kernel_path: "/vmlinuz"
        # g5k_initrd_path: "/initrd.img"
        # g5k_kernel_params: ""
        ## Environment visibility
        # g5k_visibility: "shared"

        ## Other parameters can be changed, see kameleon info ubuntu2204-dont-throw-the-stack.yaml

bootstrap:
        ### The bootstrap section takes in charge the initial installation of the
        ## system (distribution installation). No modification should be needed here.
        - "@base"

setup:
        ### The setup section is where customizations of the system take place.
        ## We can request steps from the extended recipe to be executed
        - "@base"
        ## We add steps required by our customization after or before @base. Use
        ## kameleon dryrun ubuntu2204-dont-throw-the-stack.yaml to see the resulting steps in the build.
        ## The following is given as example only, replace with your steps.
        - init:
                  - create_home:
                            - exec_in: >
                                      mkdir /home/work
                  - get_scripts:
                            - download_file_in:
                                      - http://public.sophia.grid5000.fr/~ayanovsk/dont-throw-the-stack/update-linux-tools.sh
                                      - /home/work/update-linux-tools.sh

                  - get_netstack_conf:
                            - download_file_in:
                                      - http://public.sophia.grid5000.fr/~ayanovsk/dont-throw-the-stack/netstack-config.patch
                                      - /home/work/netstack-config.patch

        - general_dep:
                  - install_dep:
                            - exec_in: >
                                      apt-get update
                            - exec_in: >
                                      DEBIAN_FRONTEND=noninteractive apt-get install -y pdsh net-tools kexec-tools libpci-dev pciutils gettext libelf-dev flex fakeroot bc ncurses-dev xz-utils build-essential wget libssl-dev python3-pip autotools-dev automake bison
                            # dpdk/mlx
                            - exec_in: >
                                      DEBIAN_FRONTEND=noninteractive apt install -y git build-essential net-tools systemd-timesyncd autotools-dev automake
                            - exec_in: >
                                      DEBIAN_FRONTEND=noninteractive apt install -y make gcc cmake pkg-config libnl-3-dev libnl-route-3-dev libnuma-dev uuid-dev libssl-dev libaio-dev libcunit1-dev libclang-dev libncurses-dev meson python3-pyelftools curl
        - ssh-accept-new:
                  - ssh_accept_new:
                            - exec_in: |
                                      echo "StrictHostKeyChecking=accept-new" >> /etc/ssh/ssh_config

        - caladan:
                  - compile:
                            - exec_in: |
                                      git clone https://github.com/shenango/caladan.git /home/work/caladan
                                      cd /home/work/caladan
                                      # because after that they introduce uintr and we dont want in our case
                                      git checkout ed67045
                                      make submodules
                                      make clean
                                      CONFIG_MLX5=y make
                                      pushd ksched
                                      make clean
                                      make
                    #       - breakpoint: "check memcached"
        - memcahced-caladan:
                  - compile:
                            - exec_in: |
                                      git clone https://github.com/shenango/memcached.git -b caladan /home/work/memcached-caladan
                                      cd /home/work/memcached-caladan
                                      ./autogen.sh
                                      ./configure --with-shenango=/home/work/caladan
                                      make -j $(nproc)

        - get_experiences:
                  - get_repo:
                            - exec_in: |
                                      git clone https://git.uwaterloo.ca/p5cai/netstack-exp.git /home/work/netstack-exp
                                      cd /home/work/netstack-exp 
                                      git apply /home/work/netstack-config.patch

export:
        ### The export section takes in charge the export of your customized Grid'5000
        ## environment. No modification should be needed here.
        - "@base"
